{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "description": "RapidRail 2026 — Origin-to-Destination Passenger Flow Bubble Matrix (Top 10 × Top 10 stations)",
  "width": 520,
  "height": 540,
  "data": {
    "values": [
      {"origin": "KG18: Bukit Bintang",       "destination": "KG18: Bukit Bintang",       "ridership": 153108},
      {"origin": "KG18: Bukit Bintang",       "destination": "KG20: Tun Razak Exchange",  "ridership": 279533},
      {"origin": "KG18: Bukit Bintang",       "destination": "KJ10: KLCC",               "ridership": 38465},
      {"origin": "KG18: Bukit Bintang",       "destination": "KJ15: KL Sentral",         "ridership": 21520},
      {"origin": "KG18: Bukit Bintang",       "destination": "KG22: Maluri",             "ridership": 294412},
      {"origin": "KG18: Bukit Bintang",       "destination": "KJ14: Pasar Seni",         "ridership": 182819},
      {"origin": "KG18: Bukit Bintang",       "destination": "KJ17: Abdullah Hukum",     "ridership": 35382},
      {"origin": "KG18: Bukit Bintang",       "destination": "KJ09: Ampang Park",        "ridership": 2942},
      {"origin": "KG18: Bukit Bintang",       "destination": "AG07: Masjid Jamek",       "ridership": 23945},
      {"origin": "KG18: Bukit Bintang",       "destination": "KG15: Muzium Negara",      "ridership": 108650},
      {"origin": "KJ10: KLCC",               "destination": "KG18: Bukit Bintang",       "ridership": 41519},
      {"origin": "KJ10: KLCC",               "destination": "KG20: Tun Razak Exchange",  "ridership": 11049},
      {"origin": "KJ10: KLCC",               "destination": "KJ10: KLCC",               "ridership": 35871},
      {"origin": "KJ10: KLCC",               "destination": "KJ15: KL Sentral",         "ridership": 228324},
      {"origin": "KJ10: KLCC",               "destination": "KG22: Maluri",             "ridership": 18827},
      {"origin": "KJ10: KLCC",               "destination": "KJ14: Pasar Seni",         "ridership": 139950},
      {"origin": "KJ10: KLCC",               "destination": "KJ17: Abdullah Hukum",     "ridership": 55650},
      {"origin": "KJ10: KLCC",               "destination": "KJ09: Ampang Park",        "ridership": 348207},
      {"origin": "KJ10: KLCC",               "destination": "AG07: Masjid Jamek",       "ridership": 78943},
      {"origin": "KJ10: KLCC",               "destination": "KG15: Muzium Negara",      "ridership": 2242},
      {"origin": "KJ15: KL Sentral",         "destination": "KG18: Bukit Bintang",       "ridership": 17328},
      {"origin": "KJ15: KL Sentral",         "destination": "KG20: Tun Razak Exchange",  "ridership": 9913},
      {"origin": "KJ15: KL Sentral",         "destination": "KJ10: KLCC",               "ridership": 246206},
      {"origin": "KJ15: KL Sentral",         "destination": "KJ15: KL Sentral",         "ridership": 53261},
      {"origin": "KJ15: KL Sentral",         "destination": "KG22: Maluri",             "ridership": 9272},
      {"origin": "KJ15: KL Sentral",         "destination": "KJ14: Pasar Seni",         "ridership": 171240},
      {"origin": "KJ15: KL Sentral",         "destination": "KJ17: Abdullah Hukum",     "ridership": 205909},
      {"origin": "KJ15: KL Sentral",         "destination": "KJ09: Ampang Park",        "ridership": 84499},
      {"origin": "KJ15: KL Sentral",         "destination": "AG07: Masjid Jamek",       "ridership": 91722},
      {"origin": "KJ15: KL Sentral",         "destination": "KG15: Muzium Negara",      "ridership": 719},
      {"origin": "KG20: Tun Razak Exchange", "destination": "KG18: Bukit Bintang",       "ridership": 304483},
      {"origin": "KG20: Tun Razak Exchange", "destination": "KG20: Tun Razak Exchange",  "ridership": 43558},
      {"origin": "KG20: Tun Razak Exchange", "destination": "KJ10: KLCC",               "ridership": 9329},
      {"origin": "KG20: Tun Razak Exchange", "destination": "KJ15: KL Sentral",         "ridership": 11846},
      {"origin": "KG20: Tun Razak Exchange", "destination": "KG22: Maluri",             "ridership": 188973},
      {"origin": "KG20: Tun Razak Exchange", "destination": "KJ14: Pasar Seni",         "ridership": 64666},
      {"origin": "KG20: Tun Razak Exchange", "destination": "KJ17: Abdullah Hukum",     "ridership": 17086},
      {"origin": "KG20: Tun Razak Exchange", "destination": "KJ09: Ampang Park",        "ridership": 312},
      {"origin": "KG20: Tun Razak Exchange", "destination": "AG07: Masjid Jamek",       "ridership": 9520},
      {"origin": "KG20: Tun Razak Exchange", "destination": "KG15: Muzium Negara",      "ridership": 72589},
      {"origin": "KJ17: Abdullah Hukum",     "destination": "KG18: Bukit Bintang",       "ridership": 40481},
      {"origin": "KJ17: Abdullah Hukum",     "destination": "KG20: Tun Razak Exchange",  "ridership": 19782},
      {"origin": "KJ17: Abdullah Hukum",     "destination": "KJ10: KLCC",               "ridership": 55003},
      {"origin": "KJ17: Abdullah Hukum",     "destination": "KJ15: KL Sentral",         "ridership": 213220},
      {"origin": "KJ17: Abdullah Hukum",     "destination": "KG22: Maluri",             "ridership": 35234},
      {"origin": "KJ17: Abdullah Hukum",     "destination": "KJ14: Pasar Seni",         "ridership": 46341},
      {"origin": "KJ17: Abdullah Hukum",     "destination": "KJ17: Abdullah Hukum",     "ridership": 30333},
      {"origin": "KJ17: Abdullah Hukum",     "destination": "KJ09: Ampang Park",        "ridership": 82590},
      {"origin": "KJ17: Abdullah Hukum",     "destination": "AG07: Masjid Jamek",       "ridership": 20104},
      {"origin": "KJ17: Abdullah Hukum",     "destination": "KG15: Muzium Negara",      "ridership": 359},
      {"origin": "KG22: Maluri",             "destination": "KG18: Bukit Bintang",       "ridership": 292672},
      {"origin": "KG22: Maluri",             "destination": "KG20: Tun Razak Exchange",  "ridership": 185621},
      {"origin": "KG22: Maluri",             "destination": "KJ10: KLCC",               "ridership": 15759},
      {"origin": "KG22: Maluri",             "destination": "KJ15: KL Sentral",         "ridership": 8318},
      {"origin": "KG22: Maluri",             "destination": "KG22: Maluri",             "ridership": 34836},
      {"origin": "KG22: Maluri",             "destination": "KJ14: Pasar Seni",         "ridership": 32629},
      {"origin": "KG22: Maluri",             "destination": "KJ17: Abdullah Hukum",     "ridership": 32196},
      {"origin": "KG22: Maluri",             "destination": "KJ09: Ampang Park",        "ridership": 561},
      {"origin": "KG22: Maluri",             "destination": "AG07: Masjid Jamek",       "ridership": 16678},
      {"origin": "KG22: Maluri",             "destination": "KG15: Muzium Negara",      "ridership": 102770},
      {"origin": "KJ09: Ampang Park",        "destination": "KG18: Bukit Bintang",       "ridership": 3361},
      {"origin": "KJ09: Ampang Park",        "destination": "KG20: Tun Razak Exchange",  "ridership": 655},
      {"origin": "KJ09: Ampang Park",        "destination": "KJ10: KLCC",               "ridership": 299885},
      {"origin": "KJ09: Ampang Park",        "destination": "KJ15: KL Sentral",         "ridership": 85393},
      {"origin": "KJ09: Ampang Park",        "destination": "KG22: Maluri",             "ridership": 1064},
      {"origin": "KJ09: Ampang Park",        "destination": "KJ14: Pasar Seni",         "ridership": 35802},
      {"origin": "KJ09: Ampang Park",        "destination": "KJ17: Abdullah Hukum",     "ridership": 82496},
      {"origin": "KJ09: Ampang Park",        "destination": "KJ09: Ampang Park",        "ridership": 44963},
      {"origin": "KJ09: Ampang Park",        "destination": "AG07: Masjid Jamek",       "ridership": 20652},
      {"origin": "KJ09: Ampang Park",        "destination": "KG15: Muzium Negara",      "ridership": 408},
      {"origin": "KJ14: Pasar Seni",         "destination": "KG18: Bukit Bintang",       "ridership": 177065},
      {"origin": "KJ14: Pasar Seni",         "destination": "KG20: Tun Razak Exchange",  "ridership": 70645},
      {"origin": "KJ14: Pasar Seni",         "destination": "KJ10: KLCC",               "ridership": 133113},
      {"origin": "KJ14: Pasar Seni",         "destination": "KJ15: KL Sentral",         "ridership": 171458},
      {"origin": "KJ14: Pasar Seni",         "destination": "KG22: Maluri",             "ridership": 30362},
      {"origin": "KJ14: Pasar Seni",         "destination": "KJ14: Pasar Seni",         "ridership": 66410},
      {"origin": "KJ14: Pasar Seni",         "destination": "KJ17: Abdullah Hukum",     "ridership": 40673},
      {"origin": "KJ14: Pasar Seni",         "destination": "KJ09: Ampang Park",        "ridership": 31551},
      {"origin": "KJ14: Pasar Seni",         "destination": "AG07: Masjid Jamek",       "ridership": 31795},
      {"origin": "KJ14: Pasar Seni",         "destination": "KG15: Muzium Negara",      "ridership": 15812},
      {"origin": "KG15: Muzium Negara",      "destination": "KG18: Bukit Bintang",       "ridership": 121583},
      {"origin": "KG15: Muzium Negara",      "destination": "KG20: Tun Razak Exchange",  "ridership": 88025},
      {"origin": "KG15: Muzium Negara",      "destination": "KJ10: KLCC",               "ridership": 4706},
      {"origin": "KG15: Muzium Negara",      "destination": "KJ15: KL Sentral",         "ridership": 648},
      {"origin": "KG15: Muzium Negara",      "destination": "KG22: Maluri",             "ridership": 104677},
      {"origin": "KG15: Muzium Negara",      "destination": "KJ14: Pasar Seni",         "ridership": 24422},
      {"origin": "KG15: Muzium Negara",      "destination": "KJ17: Abdullah Hukum",     "ridership": 656},
      {"origin": "KG15: Muzium Negara",      "destination": "KJ09: Ampang Park",        "ridership": 725},
      {"origin": "KG15: Muzium Negara",      "destination": "AG07: Masjid Jamek",       "ridership": 1563},
      {"origin": "KG15: Muzium Negara",      "destination": "KG15: Muzium Negara",      "ridership": 112351},
      {"origin": "MR06: Bukit Bintang",      "destination": "KG18: Bukit Bintang",       "ridership": 157},
      {"origin": "MR06: Bukit Bintang",      "destination": "KG20: Tun Razak Exchange",  "ridership": 340},
      {"origin": "MR06: Bukit Bintang",      "destination": "KJ10: KLCC",               "ridership": 1014},
      {"origin": "MR06: Bukit Bintang",      "destination": "KJ15: KL Sentral",         "ridership": 80},
      {"origin": "MR06: Bukit Bintang",      "destination": "KG22: Maluri",             "ridership": 883},
      {"origin": "MR06: Bukit Bintang",      "destination": "KJ14: Pasar Seni",         "ridership": 713},
      {"origin": "MR06: Bukit Bintang",      "destination": "KJ17: Abdullah Hukum",     "ridership": 145},
      {"origin": "MR06: Bukit Bintang",      "destination": "KJ09: Ampang Park",        "ridership": 75},
      {"origin": "MR06: Bukit Bintang",      "destination": "AG07: Masjid Jamek",       "ridership": 9543},
      {"origin": "MR06: Bukit Bintang",      "destination": "KG15: Muzium Negara",      "ridership": 137}
    ]
  },
  "mark": {
    "type": "circle",
    "opacity": 0.85,
    "stroke": "#ffffff",
    "strokeWidth": 0.3,
    "strokeOpacity": 0.15
  },
  "encoding": {
    "x": {
      "field": "origin",
      "type": "nominal",
      "title": "Origin Station",
      "sort": [
        "KG18: Bukit Bintang",
        "KJ10: KLCC",
        "KJ15: KL Sentral",
        "KG20: Tun Razak Exchange",
        "KJ17: Abdullah Hukum",
        "KG22: Maluri",
        "KJ09: Ampang Park",
        "KJ14: Pasar Seni",
        "KG15: Muzium Negara",
        "MR06: Bukit Bintang"
      ],
      "axis": {
        "labelAngle": -40,
        "labelFontSize": 11,
        "labelLimit": 160,
        "titleFontSize": 12,
        "titleFontWeight": "bold",
        "titlePadding": 12,
        "gridColor": "#e8e8e8",
        "gridOpacity": 0.6,
        "domainColor": "#cccccc",
        "tickColor": "#cccccc"
      }
    },
    "y": {
      "field": "destination",
      "type": "nominal",
      "title": "Destination Station",
      "sort": [
        "KG18: Bukit Bintang",
        "KG20: Tun Razak Exchange",
        "KJ10: KLCC",
        "KJ15: KL Sentral",
        "KG22: Maluri",
        "KJ14: Pasar Seni",
        "KJ17: Abdullah Hukum",
        "KJ09: Ampang Park",
        "AG07: Masjid Jamek",
        "KG15: Muzium Negara"
      ],
      "axis": {
        "labelFontSize": 11,
        "labelLimit": 180,
        "titleFontSize": 12,
        "titleFontWeight": "bold",
        "titlePadding": 12,
        "gridColor": "#e8e8e8",
        "gridOpacity": 0.6,
        "domainColor": "#cccccc",
        "tickColor": "#cccccc"
      }
    },
    "size": {
      "field": "ridership",
      "type": "quantitative",
      "title": "Total Passengers",
      "scale": {
        "type": "sqrt",
        "range": [15, 2000]
      },
      "legend": {
        "title": "Passengers",
        "format": "~s",
        "orient": "right",
        "titleFontSize": 11,
        "labelFontSize": 10
      }
    },
    "color": {
      "value": "#08306b"
    },
    "tooltip": [
      {"field": "origin",      "type": "nominal",      "title": "Origin"},
      {"field": "destination", "type": "nominal",      "title": "Destination"},
      {"field": "ridership",   "type": "quantitative", "title": "Passengers", "format": ",.0f"}
    ]
  },
  "config": {
    "view": {
      "stroke": "transparent"
    }
  }
}
